class GamblePlayer extends Player{
  -chips: number
  -bet: number
  +getBet(): number
  +setBet(): void
  +getChips(): number
  +setChips(): void
  {abstract}getHandScore(): number
  {abstract}updateChips(): void
}
