class PokerPlayerAction extends AbstractPokerPlayerAction{
  {static}betOneChip: string
  {static}changeCards: string
}

class PokerTable extends AbstractPokerTable{ 
  +betOneChip(player: Player):  void
  +changeCards(player: Player , toChangeCards: Cards[]): void
}


class PokerPlayer extends AbstractPokerPlayer{}

PokerTable *-- PokerPlayer
PokerPlayer -- PokerPlayerAction
