class Table{
  -deck: Deck[]
  -players: Player[]
  -gamePhase: string
  -isRoundOver: boolean
  {abstract}clearTableForNewGame(): void 
  {abstract}assignPlayersHand(): void
  +getGamePhase(): string
  +setGamePhase(): string
  +getUser(): Player
  {abstract}initDeck(): void
  +getIsRoundOver(): boolean
  {abstract}setIsRoundOver(): void
  {abstract}setPlayersActionRoundOver(): void
  +processAfterRoundOver(): void
}
