class TexasPokerPlayerAction extends PlayerAction{}
class TexasPokerTable extends AbstractPokerTable{
  -communityCards: Card[]
  +getCommunityCards(): Card[]
  +setCommunityCards(): void

}
class TexasPokerPlayer extends GamblePlayer{}


 TexasPokerTable *-- TexasPokerPlayer
 TexasPokerPlayer -- TexasPokerPlayerAction
